$HTTP["url"] =~ "^/vnstat/" {
  alias.url = ( "/vnstat/" => "/var/www/vnstat-web/" )
}

$HTTP["url"] !~ "^/vnstat/" {
  alias.url += ( "/" => "/var/www/vnstat-web/" )
}

server.modules += ( "mod_alias", "mod_cgi" )
alias.url += ( "/cgi-bin/" => "/usr/lib/cgi-bin/" )
$HTTP["url"] =~ "^/cgi-bin/" {
  cgi.assign = ( "" => "" )
}
